server:
  port: 9000
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: Pass2020!
#    key-store-type: PKCS12
#    key-alias: myssl

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://sincroled.com.br/"]
            #           allowedOrigins: [ "*"]
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - OPTIONS
              - PUT
