server:
  port: 9000
spring:
  codec:
    max-in-memory-size: 10MB
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
##          issuer-uri: http://localhost:8080/realms/master
#          jwk-set-uri: http://localhost:8080/realms/localhost/protocol/openid-connect/certs