server:
  port: 9000
  servlet:
    context-path: /api

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://169.150.1.85","http://vps55601.publiccloud.com.br", "http://localhost:4200", "http://sincroled.com.br", "https://sincroled.com.br"]
            #           allowedOrigins: [ "*"]
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - OPTIONS
              - PUT